---
language: java
jdk:
- oraclejdk8
env:
  global:
  - MONGO_REPO="http://repo.mongodb.com/apt/ubuntu"
  - REPO_TYPE="precise/mongodb-enterprise/2.6 multiverse"
  - SOURCES_LOC="/etc/apt/sources.list.d/mongodb-enterprise.list"
  - KEY_SERVER="hkp://keyserver.ubuntu.com:80"
  - MONGOD_PARAMS="--setParameter=enableTestCommands=1"
  - MONGOD_OPTS="--dbpath ./data --fork --logpath mongod.log ${MONGOD_PARAMS}"
  - TERM=dumb
before_install:
- sudo apt-key adv --keyserver ${KEY_SERVER} --recv 7F0CEB10
- echo "deb ${MONGO_REPO} ${REPO_TYPE}" | sudo tee ${SOURCES_LOC}
- sudo apt-get update -qq
install:
- sudo apt-get install mongodb-enterprise-server
- sudo stop mongod
- mkdir data
before_script:
- mongod ${MONGOD_OPTS}
script:
- "./gradlew -q assemble"
- "./gradlew check -i -S -Pquicktest=true"
