---
language: java
jdk:
- oraclejdk7
services:
- mongodb
before_script:
- 'mongo admin --eval ''db.runCommand({setParameter : 1, textSearchEnabled : true})'''
install: "./gradlew -q assemble"
script: "./gradlew -q check"
